BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB

XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
            XXX XXX XXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

BBBBBBBB