# Generated by Django 3.1.7 on 2021-03-04 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='when',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='when'),
        ),
    ]
