# Generated by Django 3.1.7 on 2021-03-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.spot'),
        ),
    ]
