# Generated by Django 3.1.7 on 2021-04-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210401_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='x',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='spot',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
