# Generated by Django 3.1.7 on 2021-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210401_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='windfinder_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
